### ISSUE TITLE
[Question] How can i use Where clause ?

### ISSUE THREAD

**Issue by agentlimit** [thombashi/SimpleSQLite#73]
When using multiple WHERE  clause  how can  make WHERE statement including AND or OR ?

sql statement 
select * from tablename where col1="1" AND col2="2";

simplesqlite 
con=SimpleSqlite("testtable", "r)
con.select_as_dict("tablename", where=Where(key="col1", value="1" ) )  ???
     --> select * tablename where col1="1" 
How can I write  Where statement completely???
Thanks

**Comment by thombashi** [comment]
@agentlimit 
You can do that by [And](https://simplesqlite.readthedocs.io/en/latest/pages/reference/query.html#simplesqlite.query.And)/[Or](https://simplesqlite.readthedocs.io/en/latest/pages/reference/query.html#simplesqlite.query.Or) query classes. For example:

```py
from simplesqlite.query import And, Where
...
con.select_as_dict("tablename", where=And([Where(key="col1", value="1" ), Where(key="col2", value="2")])
```

**Comment by agentlimit** [comment]
Thanks.  It works  well.
