### ISSUE TITLE
How delete something via ORM?

### ISSUE THREAD

**Issue by GOOD-Stuff** [thombashi/SimpleSQLite#77]
Hi! It is really useful and cool library! 
Please, give me one point: how can I delete records from table via ORM? 
I can't find the corresponding call.

**Comment by GOOD-Stuff** [comment]
I [found](https://github.com/thombashi/SimpleSQLite/blob/master/simplesqlite/core.py#L701) that I can delete records via connection object. But it may be useful have the same functional in ORM.

**Comment by thombashi** [comment]
@GOOD-Stuff 
Thank you for your feedback.
I added the `delete` method for ORM at `SimpleSQLite 1.5.0`.
